name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.8.5

- pip:
  # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults
- sklearn=0.24.2
- Imblearn=0.8.0
- joblib=0.13.2
- numpy=1.19.2
- pandas=1.1.3
- matplotlib=3.3.2
- seaborn=0.9.0
